<a href="https://colab.research.google.com/github/BryanVerduga/recibirinfo/blob/main/Tarea2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Tarea2


Crea una matriz de calificaciones de 5x5 con datos generados aleatoriamente. Luego, utiliza la función mean() para calcular la calificación media de cada usuario.

In [5]:
import numpy as np

#crear matriz de calificaciones de 5x5 con datos aleatorios entre 1 y 5
calificaciones = np.random.randint(1, 6, size=(5, 5))
#guardar matriz en archivo
np.save('matriz_calificaciones.npy', calificaciones) #guardamos para usar en ejercicio 3

print("Matriz de calificaciones:")
print(calificaciones)

#calcular la calificación media de cada usuario (filas)
calificacion_media_por_usuario = np.mean(calificaciones, axis=1)

print("\nCalificación media por usuario:")
print(calificacion_media_por_usuario)

Matriz de calificaciones:
[[3 4 1 5 5]
 [4 4 4 3 4]
 [5 1 3 2 4]
 [2 3 5 2 4]
 [2 5 2 2 4]]

Calificación media por usuario:
[3.6 3.8 3.  3.2 3. ]


Implementa el algoritmo de los N-primeros. Dada una matriz de calificaciones y un número N, tu función debe devolver los N primeros elementos recomendados para cada usuario.

In [6]:
import numpy as np

def recomendar_N_primeros(calificaciones, N):
    #calcular la calificación media de cada usuario (filas)
    calificacion_media_por_usuario = np.mean(calificaciones, axis=1)

    #obtener los índices de los N primeros elementos recomendados para cada usuario
    indices_recomendados = np.argsort(calificacion_media_por_usuario)[::-1][:N]

    #devolver los N primeros elementos recomendados para cada usuario
    recomendados_por_usuario = []
    for usuario in range(len(calificaciones)):
        recomendados_por_usuario.append(indices_recomendados)

    return recomendados_por_usuario

#ejemplo de uso
calificaciones = np.array([
    [5, 3, 2, 4, 1],
    [1, 2, 3, 4, 5],
    [3, 4, 2, 1, 5],
    [4, 2, 1, 3, 5],
    [2, 4, 5, 3, 1]
])

N = 3  #número de elementos a recomendar por usuario

recomendaciones = recomendar_N_primeros(calificaciones, N)

print("Recomendaciones:")
for usuario, recomendados in enumerate(recomendaciones):
    print(f"Usuario {usuario + 1}: {recomendados}")


Recomendaciones:
Usuario 1: [4 3 2]
Usuario 2: [4 3 2]
Usuario 3: [4 3 2]
Usuario 4: [4 3 2]
Usuario 5: [4 3 2]


Utiliza la descomposición en valores singulares (SVD) para hacer recomendaciones basadas en la matriz de calificaciones que creaste en el Ejercicio 1. Compara los resultados con los obtenidos en el Ejercicio 2.

In [8]:
import numpy as np

#cargar matriz desde archivo
calificaciones = np.load('matriz_calificaciones.npy')

def recomendaciones_svd(matriz_calificaciones, n):
    #realizar descomposición en valores singulares (SVD)
    U, sigma, Vt = np.linalg.svd(matriz_calificaciones)
    
    #obtener la matriz de calificaciones reconstruida
    matriz_reconstruida = U.dot(np.diag(sigma)).dot(Vt)
    
    #obtener las recomendaciones para cada usuario
    recomendaciones = []
    for i in range(matriz_calificaciones.shape[0]):
        usuario = matriz_reconstruida[i, :]
        indices_top_n = np.argsort(usuario)[-n:]
        recomendaciones.append(indices_top_n)
    
    return recomendaciones

#ejemplo de uso con n=2
n = 2
resultado = recomendaciones_svd(calificaciones, n)

#imprimir los N primeros elementos recomendados para cada usuario
for i, rec in enumerate(resultado):
    print(f"Usuario {i+1}: {rec}")

Usuario 1: [4 3]
Usuario 2: [1 2]
Usuario 3: [4 0]
Usuario 4: [4 2]
Usuario 5: [4 1]
